"""
Translates one intermediate test definition into a real, runnable Cypress
spec file (.cy.js). Every interaction goes through the cy.resolveTarget()
custom command (cypress/support/commands.js) — the JS equivalent of
locator_resolution/strategies/accessibility_tree.py's fallback chain,
since Cypress has no built-in semantic-label-to-selector translation
either (see that module's docstring for why this is genuinely harder
than Playwright's case).

Values are embedded via json.dumps, which produces valid JS object/string
literal syntax directly (JSON is a syntactic subset of JS for the plain
strings this format ever uses) — same reasoning as both Python adapters'
_py() helper, and the same real bug (repr()-style quote collision on
apostrophes) it was written to avoid.
"""
from __future__ import annotations

import json
from typing import Any

from adapters.base_adapter import BaseAdapter


def _js(value: Any) -> str:
    return json.dumps(value)


_HEADER = """/**
 * Auto-generated by universal-test-framework's Cypress adapter.
 * Do not edit by hand — regenerate from the intermediate test definition
 * instead, or your changes will be lost on the next generation run.
 *
 * Run with:  npx cypress run --spec "{spec_path}"
 * Target site (Cypress baseUrl) is read from the TEST_BASE_URL env var
 * (default: http://localhost:8000) — see cypress.config.js.
 */
describe({test_name_json}, () => {{
  it("runs", () => {{
"""

_FOOTER = """  });
});
"""


class CypressAdapter(BaseAdapter):
    name = "cypress"
    file_extension = ".cy.js"

    def generate(self, test_def: dict[str, Any]) -> str:
        slug = _slug(test_def["test_name"])
        spec_path = f"generated/test_{slug}.cy.js"
        lines = [_HEADER.format(spec_path=spec_path, test_name_json=_js(test_def["test_name"]))]

        for step in test_def["steps"]:
            lines.append(self._generate_step(step))

        lines.append(_FOOTER)
        return "".join(lines)

    def _generate_step(self, step: dict[str, Any]) -> str:
        action = step["action"]
        target = step.get("target")
        value = step.get("value")

        if action == "navigate":
            return f'    cy.visit({_js(target["value"])});\n'

        if action == "fill":
            return f'    cy.resolveTarget({_js(target)}).clear().type({_js(value)});\n'

        if action == "click":
            return f'    cy.resolveTarget({_js(target)}).click();\n'

        if action == "select":
            return f'    cy.resolveTarget({_js(target)}).select({_js(value)});\n'

        if action == "check":
            return f'    cy.resolveTarget({_js(target)}).check();\n'

        if action == "uncheck":
            return f'    cy.resolveTarget({_js(target)}).uncheck();\n'

        if action == "assert_visible":
            return f'    cy.resolveTarget({_js(target)}).should("be.visible");\n'

        if action == "assert_text":
            return f'    cy.resolveTarget({_js(target)}).should("contain.text", {_js(value)});\n'

        if action == "assert_url":
            return f'    cy.url().should("include", {_js(value)});\n'

        raise ValueError(f"CypressAdapter: unsupported action {action!r}")


def _slug(test_name: str) -> str:
    slug = "".join(c if c.isalnum() else "_" for c in test_name.lower())
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_")
