"""
Translates one intermediate test definition into a real, standalone,
runnable Playwright (Python, sync API) script.

Playwright's own get_by_role/get_by_label/get_by_text primitives already
do semantic, accessibility-tree-based element lookup — see
locator_resolution/playwright_resolver.py's module docstring for exactly
why that makes this adapter's job comparatively simple compared to
Selenium/Cypress. Generated code imports that resolver rather than
inlining raw selectors, so every generated script gets the same fallback
chain and hint support.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from adapters.base_adapter import BaseAdapter

# The framework's own install location at generation time — embedded so
# the generated script can find locator_resolution regardless of where the
# generated file itself ends up being copied to run from. This means a
# moved/renamed framework checkout breaks generated scripts until
# regenerated; see docs/getting_started.md for the alternative
# (pip install -e . the framework so it's importable without this at all).
_FRAMEWORK_ROOT = Path(__file__).resolve().parent.parent


def _py(value: Any) -> str:
    """
    Embed a Python value as generated-code-safe source text — json.dumps,
    not repr(). repr() picks its quote character based on content (double
    quotes when the string itself contains a single quote, e.g. "we'll"),
    which breaks when nested inside another f-string using that same quote
    character (a real bug found during this project's own adapter testing,
    on exactly this apostrophe case). json.dumps always double-quotes and
    only ever escapes `"` and `\\`, so nesting it is always safe; JSON
    string/object literal syntax is valid Python source either way.
    """
    return json.dumps(value)

_HEADER = '''"""
Auto-generated by universal-test-framework's Playwright adapter.
Do not edit by hand — regenerate from the intermediate test definition
instead, or your changes will be lost on the next generation run.

Run with:  python {filename}
Target site is read from the TEST_BASE_URL env var (default: http://localhost:8000).
"""
import os
import re
import sys

from playwright.sync_api import sync_playwright, expect

sys.path.insert(0, {framework_root_json})
from locator_resolution.playwright_resolver import resolve

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8000")


def test_{test_slug}(page):
'''

_FOOTER = '''

if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=os.environ.get("HEADED") != "1")
        page = browser.new_page()
        try:
            test_{test_slug}(page)
            print("PASSED: " + {test_name_json})
        finally:
            browser.close()
'''


class PlaywrightAdapter(BaseAdapter):
    name = "playwright"
    file_extension = ".py"

    def generate(self, test_def: dict[str, Any]) -> str:
        slug = _slug(test_def["test_name"])
        filename = f"test_{slug}.py"
        lines = [_HEADER.format(filename=filename, framework_root_json=_py(str(_FRAMEWORK_ROOT)), test_slug=slug)]

        for step in test_def["steps"]:
            lines.append(self._generate_step(step))

        lines.append(_FOOTER.format(test_slug=slug, test_name_json=_py(test_def["test_name"])))
        return "".join(lines)

    def _generate_step(self, step: dict[str, Any]) -> str:
        action = step["action"]
        target = step.get("target")
        value = step.get("value")

        if action == "navigate":
            return f'    page.goto(BASE_URL + {_py(target["value"])})\n'

        if action == "fill":
            return f'    resolve(page, {_py(target)}).fill({_py(value)})\n'

        if action == "click":
            return f'    resolve(page, {_py(target)}).click()\n'

        if action == "select":
            return f'    resolve(page, {_py(target)}).select_option(label={_py(value)})\n'

        if action == "check":
            return f'    resolve(page, {_py(target)}).check()\n'

        if action == "uncheck":
            return f'    resolve(page, {_py(target)}).uncheck()\n'

        if action == "assert_visible":
            return f'    expect(resolve(page, {_py(target)})).to_be_visible()\n'

        if action == "assert_text":
            return f'    expect(resolve(page, {_py(target)})).to_contain_text({_py(value)})\n'

        if action == "assert_url":
            # expect(page).to_have_url(...) polls (default 5s) instead of
            # checking page.url once -- a real SPA (client-side route change
            # after an async API call, e.g. React Router post-login) can take
            # a beat to update the URL, and a one-shot check races that.
            # Found via this framework's own real-app (SCIP) demonstration.
            return f'    expect(page).to_have_url(re.compile(re.escape({_py(value)})))\n'

        raise ValueError(f"PlaywrightAdapter: unsupported action {action!r}")


def _slug(test_name: str) -> str:
    slug = "".join(c if c.isalnum() else "_" for c in test_name.lower())
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_")
