"""
Translates one intermediate test definition into a real, standalone,
runnable Playwright (Python, sync API) script.

Playwright's own get_by_role/get_by_label/get_by_text primitives already
do semantic, accessibility-tree-based element lookup — see
locator_resolution/playwright_resolver.py's module docstring for exactly
why that makes this adapter's job comparatively simple compared to
Selenium/Cypress. Generated code imports that resolver rather than
inlining raw selectors, so every generated script gets the same fallback
chain and hint support.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from adapters.base_adapter import BaseAdapter

# The framework's own install location at generation time — embedded so
# the generated script can find locator_resolution regardless of where the
# generated file itself ends up being copied to run from. This means a
# moved/renamed framework checkout breaks generated scripts until
# regenerated; see docs/getting_started.md for the alternative
# (pip install -e . the framework so it's importable without this at all).
_FRAMEWORK_ROOT = Path(__file__).resolve().parent.parent

_HEADER = '''"""
Auto-generated by universal-test-framework's Playwright adapter.
Do not edit by hand — regenerate from the intermediate test definition
instead, or your changes will be lost on the next generation run.

Run with:  python {filename}
Target site is read from the TEST_BASE_URL env var (default: http://localhost:8000).
"""
import os
import sys

from playwright.sync_api import sync_playwright, expect

sys.path.insert(0, {framework_root!r})
from locator_resolution.playwright_resolver import resolve

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8000")


def test_{test_slug}(page):
'''

_FOOTER = '''

if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=os.environ.get("HEADED") != "1")
        page = browser.new_page()
        try:
            test_{test_slug}(page)
            print("PASSED: {test_name}")
        finally:
            browser.close()
'''


class PlaywrightAdapter(BaseAdapter):
    name = "playwright"
    file_extension = ".py"

    def generate(self, test_def: dict[str, Any]) -> str:
        slug = _slug(test_def["test_name"])
        filename = f"test_{slug}.py"
        lines = [_HEADER.format(filename=filename, framework_root=str(_FRAMEWORK_ROOT), test_slug=slug)]

        for step in test_def["steps"]:
            lines.append(self._generate_step(step))

        lines.append(_FOOTER.format(test_slug=slug, test_name=test_def["test_name"]))
        return "".join(lines)

    def _generate_step(self, step: dict[str, Any]) -> str:
        action = step["action"]
        target = step.get("target")
        value = step.get("value")

        if action == "navigate":
            return f'    page.goto(BASE_URL + {target["value"]!r})\n'

        if action == "fill":
            return f'    resolve(page, {target!r}).fill({value!r})\n'

        if action == "click":
            return f'    resolve(page, {target!r}).click()\n'

        if action == "select":
            return f'    resolve(page, {target!r}).select_option(label={value!r})\n'

        if action == "check":
            return f'    resolve(page, {target!r}).check()\n'

        if action == "uncheck":
            return f'    resolve(page, {target!r}).uncheck()\n'

        if action == "assert_visible":
            return f'    expect(resolve(page, {target!r})).to_be_visible()\n'

        if action == "assert_text":
            return f'    expect(resolve(page, {target!r})).to_contain_text({value!r})\n'

        if action == "assert_url":
            return (
                f'    assert {value!r} in page.url, '
                f'f"Expected URL to contain {value!r}, got {{page.url}}"\n'
            )

        raise ValueError(f"PlaywrightAdapter: unsupported action {action!r}")


def _slug(test_name: str) -> str:
    slug = "".join(c if c.isalnum() else "_" for c in test_name.lower())
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_")
