"""
Translates one intermediate test definition into a real, standalone,
runnable Selenium (Python) script.

Unlike the Playwright adapter, this one leans entirely on
locator_resolution/selenium_resolver.py for every single interaction —
Selenium has no built-in semantic-label-to-selector translation, so ALL
of the "hard problem" the design brief calls out lives there, not here.
This adapter's own job is just correct action->API translation once an
element handle already exists.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from adapters.base_adapter import BaseAdapter

_FRAMEWORK_ROOT = Path(__file__).resolve().parent.parent


def _py(value: Any) -> str:
    """
    Embed a Python value as generated-code-safe source text.

    repr() picks its quote character based on the string's content (double
    quotes when the string itself contains a single quote, e.g. "we'll"),
    which silently breaks when that repr output is then nested inside
    another f-string using the same quote character (found for real during
    this adapter's own testing — the "Thanks - we'll be in touch shortly."
    fixture value). json.dumps always double-quotes and only ever escapes
    `"` and `\\`, so nesting it is safe regardless of what quote characters
    the value itself contains; JSON string/object literal syntax is valid
    Python source, which is all this adapter ever needs to embed.
    """
    return json.dumps(value)

_HEADER = '''"""
Auto-generated by universal-test-framework's Selenium adapter.
Do not edit by hand — regenerate from the intermediate test definition
instead, or your changes will be lost on the next generation run.

Run with:  python {filename}
Requires: pip install selenium (Selenium Manager auto-downloads a driver
for whichever browser you already have installed — Chrome or Edge).
Target site is read from the TEST_BASE_URL env var (default: http://localhost:8000).
"""
import os
import sys

from selenium import webdriver
from selenium.webdriver.support.ui import Select

sys.path.insert(0, {framework_root_json})
from locator_resolution.selenium_resolver import resolve

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8000")


def test_{test_slug}(driver):
'''

_FOOTER = '''

if __name__ == "__main__":
    options = webdriver.ChromeOptions()
    if os.environ.get("HEADED") != "1":
        options.add_argument("--headless=new")
    driver = webdriver.Chrome(options=options)
    try:
        test_{test_slug}(driver)
        print("PASSED: " + {test_name_json})
    finally:
        driver.quit()
'''


class SeleniumAdapter(BaseAdapter):
    name = "selenium"
    file_extension = ".py"

    def generate(self, test_def: dict[str, Any]) -> str:
        slug = _slug(test_def["test_name"])
        filename = f"test_{slug}.py"
        lines = [_HEADER.format(filename=filename, framework_root_json=_py(str(_FRAMEWORK_ROOT)), test_slug=slug)]

        for step in test_def["steps"]:
            lines.append(self._generate_step(step))

        lines.append(_FOOTER.format(test_slug=slug, test_name_json=_py(test_def["test_name"])))
        return "".join(lines)

    def _generate_step(self, step: dict[str, Any]) -> str:
        action = step["action"]
        target = step.get("target")
        value = step.get("value")

        if action == "navigate":
            return f'    driver.get(BASE_URL + {_py(target["value"])})\n'

        if action == "fill":
            return f'    resolve(driver, {_py(target)}).send_keys({_py(value)})\n'

        if action == "click":
            return f'    resolve(driver, {_py(target)}).click()\n'

        if action == "select":
            return f'    Select(resolve(driver, {_py(target)})).select_by_visible_text({_py(value)})\n'

        if action == "check":
            return (
                f'    _el = resolve(driver, {_py(target)})\n'
                f'    if not _el.is_selected(): _el.click()\n'
            )

        if action == "uncheck":
            return (
                f'    _el = resolve(driver, {_py(target)})\n'
                f'    if _el.is_selected(): _el.click()\n'
            )

        if action == "assert_visible":
            return (
                f'    assert resolve(driver, {_py(target)}).is_displayed(), '
                f'"Expected element to be visible: " + {_py(str(target))}\n'
            )

        if action == "assert_text":
            return (
                f'    _text = resolve(driver, {_py(target)}).text\n'
                f'    assert {_py(value)} in _text, "Expected text " + {_py(value)} + ", got: " + _text\n'
            )

        if action == "assert_url":
            return (
                f'    assert {_py(value)} in driver.current_url, '
                f'"Expected URL to contain " + {_py(value)} + ", got " + driver.current_url\n'
            )

        raise ValueError(f"SeleniumAdapter: unsupported action {action!r}")


def _slug(test_name: str) -> str:
    slug = "".join(c if c.isalnum() else "_" for c in test_name.lower())
    while "__" in slug:
        slug = slug.replace("__", "_")
    return slug.strip("_")
