"""
Translates one intermediate test definition into a real, runnable TestNG
(Java) test class — proves the same intermediate format targets a JVM
toolchain, not just Python/JS. Uses com.utf.locator.SeleniumResolver
(runners/testng-selenium/src/main/java/com/utf/locator/), this
language's own port of the same accessibility-tree fallback-chain
philosophy as the Python/JS resolvers (see that package's own docs for
the one honest gap: no OpenCV visual fallback here yet, a real scope
boundary, not an oversight — see docs/adding_a_new_language.md).

Values are embedded via a small Java-string-literal escaper (_java_str),
same reasoning as the Python/JS adapters' _py()/_js() helpers: naive
string interpolation breaks the moment a value contains a quote
character the surrounding literal also uses.
"""
from __future__ import annotations

from typing import Any

from adapters.base_adapter import BaseAdapter


def _java_str(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def _java_map(d: dict[str, Any]) -> str:
    """Renders a flat (str -> str | nested map) dict as a Map.<String, Object>.of(...) expression."""
    parts = []
    for key, value in d.items():
        parts.append(_java_str(key))
        parts.append(_java_map(value) if isinstance(value, dict) else _java_str(str(value)))
    if not parts:
        return "Map.<String, Object>of()"
    return "Map.<String, Object>of(" + ", ".join(parts) + ")"


_HEADER = """package com.utf.generated;

import com.utf.locator.SeleniumResolver;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.Select;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.Map;

/**
 * Auto-generated by universal-test-framework's TestNG/Selenium adapter.
 * Do not edit by hand -- regenerate from the intermediate test definition
 * instead, or your changes will be lost on the next generation run.
 *
 * Target site is read from the TEST_BASE_URL env var
 * (default: http://localhost:8000).
 */
public class {class_name} {{
    private WebDriver driver;
    private static final String BASE_URL =
        System.getenv().getOrDefault("TEST_BASE_URL", "http://localhost:8000");

    @BeforeMethod
    public void setUp() {{
        ChromeOptions options = new ChromeOptions();
        if (!"1".equals(System.getenv("HEADED"))) {{
            options.addArguments("--headless=new");
        }}
        driver = new ChromeDriver(options);
    }}

    @AfterMethod
    public void tearDown() {{
        if (driver != null) driver.quit();
    }}

    @Test
    public void runs() {{
"""

_FOOTER = """    }
}
"""


class TestNGSeleniumAdapter(BaseAdapter):
    name = "testng-selenium"
    file_extension = ".java"

    def generate(self, test_def: dict[str, Any]) -> str:
        class_name = _class_name(test_def["test_name"])
        lines = [_HEADER.format(class_name=class_name)]

        for step in test_def["steps"]:
            lines.append(self._generate_step(step))

        lines.append(_FOOTER)
        return "".join(lines)

    def generate_filename(self, test_def: dict[str, Any]) -> str:
        return f"{_class_name(test_def['test_name'])}{self.file_extension}"

    def _generate_step(self, step: dict[str, Any]) -> str:
        action = step["action"]
        target = step.get("target")
        value = step.get("value")

        if action == "navigate":
            return f'        driver.get(BASE_URL + {_java_str(target["value"])});\n'

        if action == "fill":
            return f'        SeleniumResolver.resolve(driver, {_java_map(target)}).sendKeys({_java_str(value)});\n'

        if action == "click":
            return f'        SeleniumResolver.resolve(driver, {_java_map(target)}).click();\n'

        if action == "select":
            return f'        new Select(SeleniumResolver.resolve(driver, {_java_map(target)})).selectByVisibleText({_java_str(value)});\n'

        if action == "check":
            return (
                f'        WebElement el = SeleniumResolver.resolve(driver, {_java_map(target)});\n'
                f'        if (!el.isSelected()) el.click();\n'
            )

        if action == "uncheck":
            return (
                f'        WebElement el = SeleniumResolver.resolve(driver, {_java_map(target)});\n'
                f'        if (el.isSelected()) el.click();\n'
            )

        if action == "assert_visible":
            return (
                f'        Assert.assertTrue(SeleniumResolver.resolve(driver, {_java_map(target)}).isDisplayed(), '
                f'"Expected element to be visible: " + {_java_map(target)});\n'
            )

        if action == "assert_text":
            return (
                f'        String actualText = SeleniumResolver.resolve(driver, {_java_map(target)}).getText();\n'
                f'        Assert.assertTrue(actualText.contains({_java_str(value)}), '
                f'"Expected text " + {_java_str(value)} + ", got: " + actualText);\n'
            )

        if action == "assert_url":
            return (
                f'        Assert.assertTrue(driver.getCurrentUrl().contains({_java_str(value)}), '
                f'"Expected URL to contain " + {_java_str(value)} + ", got " + driver.getCurrentUrl());\n'
            )

        raise ValueError(f"TestNGSeleniumAdapter: unsupported action {action!r}")


def _class_name(test_name: str) -> str:
    words = "".join(c if c.isalnum() else " " for c in test_name).split()
    return "".join(w[:1].upper() + w[1:] for w in words) or "GeneratedTest"
