/**
 * Client-side ports of this project's Python adapters, for the static
 * GitHub Pages showcase (webshowcase/) — pure code generation only, no
 * server, no real browser execution. These mirror adapters/*.py exactly
 * (same string templates, same per-action switch); see that Python
 * source for the authoritative version this was ported from, and
 * docs/adapters.md for what each one actually does.
 *
 * "Run" isn't offered here on purpose: launching a real browser to
 * execute generated Selenium/Playwright/Cypress code is a server-side
 * operation GitHub Pages architecturally cannot provide. Clone the repo
 * and see docs/getting_started.md to actually run any of this.
 */

// json.dumps() and JSON.stringify() produce identical output for the
// plain strings/objects this format ever uses -- same reasoning as the
// Python adapters' _py()/_js() helpers (avoid repr()-style quote
// collisions), no custom escaper needed here.
function j(value) {
  return JSON.stringify(value);
}

function slug(testName) {
  let s = testName.toLowerCase().replace(/[^a-z0-9]/g, "_");
  while (s.includes("__")) s = s.replace(/__/g, "_");
  return s.replace(/^_+|_+$/g, "");
}

function className(testName) {
  const words = testName.replace(/[^a-zA-Z0-9]/g, " ").split(/\s+/).filter(Boolean);
  return words.map((w) => w[0].toUpperCase() + w.slice(1)).join("") || "GeneratedTest";
}

// ---------------------------------------------------------------------
// Manual test case (generation/manual_case_generator.py)
// ---------------------------------------------------------------------

const TARGET_PHRASE = {
  field_description: (t) => t.value,
  checkbox_description: (t) => `the "${t.value}" checkbox`,
  dropdown_description: (t) => `the "${t.value}" dropdown`,
  button_text: (t) => `the "${t.value}" button`,
  link_text: (t) => `the "${t.value}" link`,
  element_role: (t) => `the ${t.role} named "${t.name}"`,
  page_text: (t) => t.value,
};

function describeTarget(target) {
  const fn = TARGET_PHRASE[target.type];
  return fn ? fn(target) : target.value || "the element";
}

function describeStep(step) {
  const { action, target, value } = step;
  switch (action) {
    case "navigate": return `Go to ${target.value}.`;
    case "fill": return `Enter "${value}" into ${describeTarget(target)}.`;
    case "click": return `Click ${describeTarget(target)}.`;
    case "select": return `Choose "${value}" from ${describeTarget(target)}.`;
    case "check": return `Check ${describeTarget(target)}.`;
    case "uncheck": return `Uncheck ${describeTarget(target)}.`;
    case "assert_visible": return `Verify that ${describeTarget(target)} is visible.`;
    case "assert_text": return `Verify that ${describeTarget(target)} shows "${value}".`;
    case "assert_url": return `Verify the page URL contains "${value}".`;
    default: return `Unrecognized step: ${JSON.stringify(step)}`;
  }
}

export function generateManualCase(testDef) {
  const lines = [`Test Case: ${testDef.test_name}`];
  if (testDef.description) lines.push(testDef.description);
  lines.push("", "Steps:");
  testDef.steps.forEach((step, i) => lines.push(`${i + 1}. ${describeStep(step)}`));
  return lines.join("\n");
}

// ---------------------------------------------------------------------
// Playwright (adapters/playwright_adapter.py)
// ---------------------------------------------------------------------

export function generatePlaywright(testDef) {
  const testSlug = slug(testDef.test_name);
  const filename = `test_${testSlug}.py`;
  const lines = [`"""
Auto-generated by universal-test-framework's Playwright adapter.
Do not edit by hand -- regenerate from the intermediate test definition
instead, or your changes will be lost on the next generation run.

Run with:  python ${filename}
Target site is read from the TEST_BASE_URL env var (default: http://localhost:8000).
"""
import os
import re
import sys

from playwright.sync_api import sync_playwright, expect

sys.path.insert(0, ${j(".")})  # the real CLI/UI embeds an absolute path to your checkout here
from locator_resolution.playwright_resolver import resolve

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8000")


def test_${testSlug}(page):
`];

  for (const step of testDef.steps) lines.push(playwrightStep(step));

  lines.push(`

if __name__ == "__main__":
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=os.environ.get("HEADED") != "1")
        page = browser.new_page()
        try:
            test_${testSlug}(page)
            print("PASSED: " + ${j(testDef.test_name)})
        finally:
            browser.close()
`);
  return lines.join("");
}

function playwrightStep(step) {
  const { action, target, value } = step;
  switch (action) {
    case "navigate": return `    page.goto(BASE_URL + ${j(target.value)})\n`;
    case "fill": return `    resolve(page, ${j(target)}).fill(${j(value)})\n`;
    case "click": return `    resolve(page, ${j(target)}).click()\n`;
    case "select": return `    resolve(page, ${j(target)}).select_option(label=${j(value)})\n`;
    case "check": return `    resolve(page, ${j(target)}).check()\n`;
    case "uncheck": return `    resolve(page, ${j(target)}).uncheck()\n`;
    case "assert_visible": return `    expect(resolve(page, ${j(target)})).to_be_visible()\n`;
    case "assert_text": return `    expect(resolve(page, ${j(target)})).to_contain_text(${j(value)})\n`;
    case "assert_url": return `    expect(page).to_have_url(re.compile(re.escape(${j(value)})))\n`;
    default: throw new Error(`PlaywrightAdapter: unsupported action ${action}`);
  }
}

// ---------------------------------------------------------------------
// Selenium (adapters/selenium_adapter.py)
// ---------------------------------------------------------------------

export function generateSelenium(testDef) {
  const testSlug = slug(testDef.test_name);
  const filename = `test_${testSlug}.py`;
  const lines = [`"""
Auto-generated by universal-test-framework's Selenium adapter.
Do not edit by hand -- regenerate from the intermediate test definition
instead, or your changes will be lost on the next generation run.

Run with:  python ${filename}
Requires: pip install selenium (Selenium Manager auto-downloads a driver
for whichever browser you already have installed -- Chrome or Edge).
Target site is read from the TEST_BASE_URL env var (default: http://localhost:8000).
"""
import os
import sys

from selenium import webdriver
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

sys.path.insert(0, ${j(".")})  # the real CLI/UI embeds an absolute path to your checkout here
from locator_resolution.selenium_resolver import resolve

BASE_URL = os.environ.get("TEST_BASE_URL", "http://localhost:8000")


def test_${testSlug}(driver):
`];

  for (const step of testDef.steps) lines.push(seleniumStep(step));

  lines.push(`

if __name__ == "__main__":
    options = webdriver.ChromeOptions()
    if os.environ.get("HEADED") != "1":
        options.add_argument("--headless=new")
    driver = webdriver.Chrome(options=options)
    try:
        test_${testSlug}(driver)
        print("PASSED: " + ${j(testDef.test_name)})
    finally:
        driver.quit()
`);
  return lines.join("");
}

function seleniumStep(step) {
  const { action, target, value } = step;
  switch (action) {
    case "navigate": return `    driver.get(BASE_URL + ${j(target.value)})\n`;
    case "fill": return `    resolve(driver, ${j(target)}).send_keys(${j(value)})\n`;
    case "click": return `    resolve(driver, ${j(target)}).click()\n`;
    case "select": return `    Select(resolve(driver, ${j(target)})).select_by_visible_text(${j(value)})\n`;
    case "check":
      return `    _el = resolve(driver, ${j(target)})\n    if not _el.is_selected(): _el.click()\n`;
    case "uncheck":
      return `    _el = resolve(driver, ${j(target)})\n    if _el.is_selected(): _el.click()\n`;
    case "assert_visible":
      return `    assert resolve(driver, ${j(target)}).is_displayed(), "Expected element to be visible: " + ${j(JSON.stringify(target))}\n`;
    case "assert_text":
      return `    _text = resolve(driver, ${j(target)}).text\n    assert ${j(value)} in _text, "Expected text " + ${j(value)} + ", got: " + _text\n`;
    case "assert_url":
      return `    WebDriverWait(driver, 5).until(EC.url_contains(${j(value)}), "Expected URL to contain " + ${j(value)} + ", got " + driver.current_url)\n`;
    default: throw new Error(`SeleniumAdapter: unsupported action ${action}`);
  }
}

// ---------------------------------------------------------------------
// Cypress (adapters/cypress_adapter.py)
// ---------------------------------------------------------------------

export function generateCypress(testDef) {
  const testSlug = slug(testDef.test_name);
  const specPath = `generated/test_${testSlug}.cy.js`;
  const lines = [`/**
 * Auto-generated by universal-test-framework's Cypress adapter.
 * Do not edit by hand -- regenerate from the intermediate test definition
 * instead, or your changes will be lost on the next generation run.
 *
 * Run with:  npx cypress run --spec "${specPath}"
 * Target site (Cypress baseUrl) is read from the TEST_BASE_URL env var
 * (default: http://localhost:8000) -- see cypress.config.js.
 */
describe(${j(testDef.test_name)}, () => {
  it("runs", () => {
`];

  for (const step of testDef.steps) lines.push(cypressStep(step));

  lines.push(`  });
});
`);
  return lines.join("");
}

function cypressStep(step) {
  const { action, target, value } = step;
  switch (action) {
    case "navigate": return `    cy.visit(${j(target.value)});\n`;
    case "fill": return `    cy.resolveTarget(${j(target)}).clear().type(${j(value)});\n`;
    case "click": return `    cy.resolveTarget(${j(target)}).click();\n`;
    case "select": return `    cy.resolveTarget(${j(target)}).select(${j(value)});\n`;
    case "check": return `    cy.resolveTarget(${j(target)}).check();\n`;
    case "uncheck": return `    cy.resolveTarget(${j(target)}).uncheck();\n`;
    case "assert_visible": return `    cy.resolveTarget(${j(target)}).should("be.visible");\n`;
    case "assert_text": return `    cy.resolveTarget(${j(target)}).should("contain.text", ${j(value)});\n`;
    case "assert_url": return `    cy.url().should("include", ${j(value)});\n`;
    default: throw new Error(`CypressAdapter: unsupported action ${action}`);
  }
}

// ---------------------------------------------------------------------
// TestNG + Selenium / Java (adapters/testng_selenium_adapter.py)
// ---------------------------------------------------------------------

function javaStr(value) {
  const escaped = String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
  return `"${escaped}"`;
}

function javaMap(obj) {
  if (obj === null || typeof obj !== "object") return javaStr(String(obj));
  const parts = [];
  for (const [key, value] of Object.entries(obj)) {
    parts.push(javaStr(key));
    parts.push(typeof value === "object" && value !== null ? javaMap(value) : javaStr(String(value)));
  }
  if (parts.length === 0) return "Map.<String, Object>of()";
  return `Map.<String, Object>of(${parts.join(", ")})`;
}

export function generateTestNG(testDef) {
  const cls = className(testDef.test_name);
  const lines = [`package com.utf.generated;

import com.utf.locator.SeleniumResolver;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.Map;

/**
 * Auto-generated by universal-test-framework's TestNG/Selenium adapter.
 * Do not edit by hand -- regenerate from the intermediate test definition
 * instead, or your changes will be lost on the next generation run.
 *
 * Target site is read from the TEST_BASE_URL env var
 * (default: http://localhost:8000).
 */
public class ${cls} {
    private WebDriver driver;
    private static final String BASE_URL =
        System.getenv().getOrDefault("TEST_BASE_URL", "http://localhost:8000");

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        if (!"1".equals(System.getenv("HEADED"))) {
            options.addArguments("--headless=new");
        }
        driver = new ChromeDriver(options);
    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }

    @Test
    public void runs() {
`];

  for (const step of testDef.steps) lines.push(testNGStep(step));

  lines.push(`    }
}
`);
  return lines.join("");
}

function testNGStep(step) {
  const { action, target, value } = step;
  switch (action) {
    case "navigate": return `        driver.get(BASE_URL + ${javaStr(target.value)});\n`;
    case "fill": return `        SeleniumResolver.resolve(driver, ${javaMap(target)}).sendKeys(${javaStr(value)});\n`;
    case "click": return `        SeleniumResolver.resolve(driver, ${javaMap(target)}).click();\n`;
    case "select": return `        new Select(SeleniumResolver.resolve(driver, ${javaMap(target)})).selectByVisibleText(${javaStr(value)});\n`;
    case "check":
      return `        WebElement el = SeleniumResolver.resolve(driver, ${javaMap(target)});\n        if (!el.isSelected()) el.click();\n`;
    case "uncheck":
      return `        WebElement el = SeleniumResolver.resolve(driver, ${javaMap(target)});\n        if (el.isSelected()) el.click();\n`;
    case "assert_visible":
      return `        Assert.assertTrue(SeleniumResolver.resolve(driver, ${javaMap(target)}).isDisplayed(), "Expected element to be visible: " + ${javaMap(target)});\n`;
    case "assert_text":
      return `        String actualText = SeleniumResolver.resolve(driver, ${javaMap(target)}).getText();\n        Assert.assertTrue(actualText.contains(${javaStr(value)}), "Expected text " + ${javaStr(value)} + ", got: " + actualText);\n`;
    case "assert_url":
      return `        new WebDriverWait(driver, Duration.ofSeconds(5))\n            .until(ExpectedConditions.urlContains(${javaStr(value)}));\n`;
    default: throw new Error(`TestNGSeleniumAdapter: unsupported action ${action}`);
  }
}

// ---------------------------------------------------------------------
// Cucumber / Gherkin (adapters/cucumber_adapter.py)
// ---------------------------------------------------------------------

function isAction(step) {
  return !step.action.startsWith("assert");
}

function gherkinKeyword(step, isFirst) {
  if (isFirst) return "Given";
  return isAction(step) ? "When" : "Then";
}

function gherkinStepText(step) {
  const { action, target = {}, value } = step;
  const targetType = target.type;
  const hint = target.hint || {};

  switch (action) {
    case "navigate": return `the user navigates to "${target.value}"`;
    case "fill": return `the user enters "${value}" into the "${target.value}" field`;
    case "click": {
      if (targetType === "element_role") return `the user clicks the ${target.role} named "${target.name}"`;
      const noun = targetType === "button_text" ? "button" : "link";
      return `the user clicks the "${target.value}" ${noun}`;
    }
    case "select": return `the user selects "${value}" from the "${target.value}" dropdown`;
    case "check": return `the user checks the "${target.value}" checkbox`;
    case "uncheck": return `the user unchecks the "${target.value}" checkbox`;
    case "assert_visible":
      if (targetType === "element_role") return `the user should see the ${target.role} named "${target.name}"`;
      return `the user should see "${target.value}"`;
    case "assert_text":
      if ("test_id" in hint) return `the element with test id "${hint.test_id}" should show "${value}"`;
      return `the "${target.value}" should show "${value}"`;
    case "assert_url": return `the URL should contain "${value}"`;
    default: throw new Error(`CucumberAdapter: unsupported action ${action}`);
  }
}

export function generateCucumber(testDef) {
  const lines = [`Feature: ${testDef.test_name}`];
  if (testDef.description) lines.push(`  ${testDef.description}`);
  lines.push("", "  Scenario: runs");
  testDef.steps.forEach((step, i) => {
    lines.push(`    ${gherkinKeyword(step, i === 0)} ${gherkinStepText(step)}`);
  });
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------
// Adapter registry + filenames, mirroring backend/main.py's _ADAPTERS
// ---------------------------------------------------------------------

export const ADAPTERS = {
  playwright: { label: "Playwright (Python)", generate: generatePlaywright, filename: (t) => `test_${slug(t.test_name)}.py` },
  selenium: { label: "Selenium (Python)", generate: generateSelenium, filename: (t) => `test_${slug(t.test_name)}.py` },
  cypress: { label: "Cypress (JS)", generate: generateCypress, filename: (t) => `test_${slug(t.test_name)}.cy.js` },
  "testng-selenium": { label: "Selenium + TestNG (Java)", generate: generateTestNG, filename: (t) => `${className(t.test_name)}.java` },
  cucumber: { label: "Cucumber + Playwright (Gherkin)", generate: generateCucumber, filename: (t) => `test_${slug(t.test_name)}.feature` },
};
